// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoftWhatsAppCRMDash.Data;

#nullable disable

namespace SoftWhatsAppCRMDash.Migrations
{
    [DbContext(typeof(WhatsAppCrmContext))]
    [Migration("20241230152334_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Carrito", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<decimal?>("Precio")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("precio");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<decimal?>("Total")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_carrito");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProductoId");

                    b.ToTable("carrito", (string)null);
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Categorium", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int?>("PadreId")
                        .HasColumnType("integer")
                        .HasColumnName("padre_id");

                    b.HasKey("Id")
                        .HasName("pk_categoria");

                    b.HasIndex("PadreId");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero");

                    b.Property<string>("Photo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("photo");

                    b.Property<int>("WhatsappId")
                        .HasColumnType("integer")
                        .HasColumnName("whatsapp_id");

                    b.HasKey("Id")
                        .HasName("pk_cliente");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Contexto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Spromtcontext")
                        .HasColumnType("text")
                        .HasColumnName("spromtcontext");

                    b.HasKey("Id")
                        .HasName("pk_contexto");

                    b.HasIndex("ClienteId");

                    b.ToTable("contexto", (string)null);
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.EnterpriseContext", b =>
                {
                    b.Property<int>("Nid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Nid"));

                    b.Property<string>("Sdata")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sdata");

                    b.Property<string>("Spromptcontext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spromptcontext");

                    b.HasKey("Nid")
                        .HasName("enterprise_context_pkey");

                    b.ToTable("enterprise_context", (string)null);
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Entrega", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<decimal?>("Precio")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("precio");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_entrega");

                    b.ToTable("entrega", (string)null);
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_marca");

                    b.ToTable("marca", (string)null);
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Migration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Batch")
                        .HasColumnType("integer")
                        .HasColumnName("batch");

                    b.Property<string>("Migration1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("migration");

                    b.HasKey("Id")
                        .HasName("migrations_pkey");

                    b.ToTable("migrations", (string)null);
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ciudad");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<decimal>("CosteTotal")
                        .HasPrecision(16, 2)
                        .HasColumnType("numeric(16,2)")
                        .HasColumnName("coste_total");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("departamento");

                    b.Property<decimal?>("Descuento")
                        .HasPrecision(16, 2)
                        .HasColumnType("numeric(16,2)")
                        .HasColumnName("descuento");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("direccion");

                    b.Property<int?>("EntregaId")
                        .HasColumnType("integer")
                        .HasColumnName("entrega_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora");

                    b.Property<string>("NumeroOrden")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("numero_orden");

                    b.Property<decimal?>("Subtotal")
                        .HasPrecision(16, 2)
                        .HasColumnType("numeric(16,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("Id")
                        .HasName("pk_pedido");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EntregaId");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Imagen")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("imagen");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("integer")
                        .HasColumnName("marca_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Oferta")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("oferta");

                    b.Property<decimal>("Precio")
                        .HasPrecision(16, 2)
                        .HasColumnType("numeric(16,2)")
                        .HasColumnName("precio");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.HasKey("Id")
                        .HasName("pk_producto");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MarcaId");

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.ResenaProducto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("Calificacion")
                        .HasColumnType("integer")
                        .HasColumnName("calificacion");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mensaje");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("pk_resena_producto");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProductoId");

                    b.ToTable("resena_producto", (string)null);
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.SaleNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Mount")
                        .HasColumnType("numeric");

                    b.Property<string>("PayCode")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("SaleNotes");
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.SaleNoteDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SaleNoteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductId" }, "IX_SaleNoteDetails_ProductId");

                    b.HasIndex(new[] { "SaleNoteId" }, "IX_SaleNoteDetails_SaleNoteId");

                    b.ToTable("SaleNoteDetails");
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Imagen")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("imagen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Rol")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex(new[] { "Email" }, "uk_usuario_email")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Carrito", b =>
                {
                    b.HasOne("SoftWhatsAppCRMDash.Models.Cliente", "Cliente")
                        .WithMany("Carritos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carrito_cliente");

                    b.HasOne("SoftWhatsAppCRMDash.Models.Producto", "Producto")
                        .WithMany("Carritos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carrito_producto");

                    b.Navigation("Cliente");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Categorium", b =>
                {
                    b.HasOne("SoftWhatsAppCRMDash.Models.Categorium", "Padre")
                        .WithMany("InversePadre")
                        .HasForeignKey("PadreId")
                        .HasConstraintName("fk_padre_categoria");

                    b.Navigation("Padre");
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Contexto", b =>
                {
                    b.HasOne("SoftWhatsAppCRMDash.Models.Cliente", "Cliente")
                        .WithMany("Contextos")
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("fk_contexto_cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Pedido", b =>
                {
                    b.HasOne("SoftWhatsAppCRMDash.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_cliente");

                    b.HasOne("SoftWhatsAppCRMDash.Models.Entrega", "Entrega")
                        .WithMany("Pedidos")
                        .HasForeignKey("EntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_pedido_entrega");

                    b.Navigation("Cliente");

                    b.Navigation("Entrega");
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Producto", b =>
                {
                    b.HasOne("SoftWhatsAppCRMDash.Models.Categorium", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_producto_categoria");

                    b.HasOne("SoftWhatsAppCRMDash.Models.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_producto_marca");

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.ResenaProducto", b =>
                {
                    b.HasOne("SoftWhatsAppCRMDash.Models.Cliente", "Cliente")
                        .WithMany("ResenaProductos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_resena_producto_cliente");

                    b.HasOne("SoftWhatsAppCRMDash.Models.Producto", "Producto")
                        .WithMany("ResenaProductos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_resena_producto_producto");

                    b.Navigation("Cliente");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.SaleNote", b =>
                {
                    b.HasOne("SoftWhatsAppCRMDash.Models.Cliente", "Client")
                        .WithMany("SaleNotes")
                        .HasForeignKey("ClientId")
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.SaleNoteDetail", b =>
                {
                    b.HasOne("SoftWhatsAppCRMDash.Models.Producto", "Product")
                        .WithMany("SaleNoteDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftWhatsAppCRMDash.Models.SaleNote", "SaleNote")
                        .WithMany("SaleNoteDetails")
                        .HasForeignKey("SaleNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SaleNote");
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Categorium", b =>
                {
                    b.Navigation("InversePadre");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Cliente", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("Contextos");

                    b.Navigation("Pedidos");

                    b.Navigation("ResenaProductos");

                    b.Navigation("SaleNotes");
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Entrega", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.Producto", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("ResenaProductos");

                    b.Navigation("SaleNoteDetails");
                });

            modelBuilder.Entity("SoftWhatsAppCRMDash.Models.SaleNote", b =>
                {
                    b.Navigation("SaleNoteDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
